// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Contract struct {
	ContractID    string
	Name          string
	WebsocketOpen bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Trade struct {
	ID          string
	UserID      string
	Contract    string
	Side        string
	Quantity    float64
	BoughtPrice sql.NullFloat64
	SoldPrice   sql.NullFloat64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID             string
	Email          string
	Name           string
	HashedPassword string
	Balance        float64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
