GET http://localhost:8081/api/trades HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnb2xhbmFfc2VydmVyIiwic3ViIjoiYWU5MmNlZGYtOTMwMi00NmIxLWI0N2QtODlmYWFhNjIxMzhlIiwiZXhwIjoxNzU2NTEwMjg4LCJpYXQiOjE3NTY1MDg0ODh9.glVpeseVF4wHIav7bl6k2AlwTkeoBf4nDhmNUCWi57c

{
  "email": "test@test.com",
  "password": "test"
}